// frameworks/keyed/solid-3/src/main.jsx
import { createRoot, createState } from 'solid-js';

let idCounter = 1;
const adjectives = ["pretty", "large", "big", "small", "tall", "short", "long", "handsome", "plain", "quaint", "clean", "elegant", "easy", "angry", "crazy", "helpful", "mushy", "odd", "unsightly", "adorable", "important", "inexpensive", "cheap", "expensive", "fancy"],
  colours = ["red", "yellow", "blue", "green", "pink", "brown", "purple", "brown", "white", "black", "orange"],
  nouns = ["table", "chair", "house", "bbq", "desk", "car", "pony", "cookie", "sandwich", "burger", "pizza", "mouse", "keyboard"];

let seed = 0;
// random function is replaced to remove any randomness from the benchmark.
const random = (max) => seed++ % max;

function buildData(count) {
  let data = new Array(count);
  for (let i = 0; i < count; i++) {
    data[i] = {
      id: idCounter++,
      label: `${adjectives[random(adjectives.length)]} ${colours[random(colours.length)]} ${nouns[random(nouns.length)]}`
    }
  }
  return data;
}

const Button = ({ id, text, fn }) => <div class='col-sm-6 smallpad'><button id={id} class='btn btn-primary btn-block' type='button' onClick={fn}>{text}</button></div>;
const RemoveIcon = ({ preload }) => <span class={(preload ? 'preloadicon glyphicon glyphicon-remove' : 'glyphicon glyphicon-remove')} aria-hidden="true"></span>;
const Cell = ({ className, children }) => <td class={(className)}>{children}</td>;
const Row = ({ state, row, select, remove }) => (
  <tr class={(state.selected === row.id ? 'danger' : '')}>
    <Cell className='col-md-1'>{(row.id)}</Cell>
    <Cell className='col-md-4'><a onClick={() => { select(row.id); }}>{(row.label)}</a></Cell>
    <Cell className='col-md-1'><a onClick={() => { remove(row.id); }}><RemoveIcon preload={false} /></a></Cell>
    <Cell className='col-md-6'></Cell>
  </tr>
);

const App = () => {
  const [state, setState] = createState({ data: [], selected: null }),
    run = () => setState({ data: buildData(1000), selected: null }),
    runLots = () => setState({ data: buildData(10000), selected: null }),
    add = () => setState('data', d => [...d, ...buildData(1000)]),
    update = () => setState('data', { by: 10 }, 'label', l => l + ' !!!'),
    swapRows = () => setState('data', d => d.length > 998 ? { 1: d[998], 998: d[1] } : d),
    clear = () => setState({ data: [], selected: null }),
    select = (id) => setState('selected', id),
    remove = (id) => setState('data', d => {
      const idx = d.findIndex(d => d.id === id);
      return [...d.slice(0, idx), ...d.slice(idx + 1)];
    });

  return <div class='container'>
    <div class='jumbotron'><div class='row'>
      <div class='col-md-6'><h1>SolidJS Keyed</h1></div>
      <div class='col-md-6'><div class='row'>
        <Button id='run' text='Create 1,000 rows' fn={run} />
        <Button id='runlots' text='Create 10,000 rows' fn={runLots} />
        <Button id='add' text='Append 1,000 rows' fn={add} />
        <Button id='update' text='Update every 10th row' fn={update} />
        <Button id='clear' text='Clear' fn={clear} />
        <Button id='swaprows' text='Swap Rows' fn={swapRows} />
      </div></div>
    </div></div>
    <table class='table table-hover table-striped test-data'><tbody>
      <$ each={state.data}>{row => <Row state={state} row={row} select={select} remove={remove} />}</$>
    </tbody></table>
    <RemoveIcon preload={true} />
  </div>
}

createRoot(() => document.getElementById("main").appendChild(<App />))

// frameworks/keyed/react-redux/src/main.jsx
import React, { useCallback } from "react";
import ReactDOM from "react-dom";
import { createStore } from "redux";
import { Provider, useDispatch, useSelector } from "react-redux";

const A = ["pretty", "large", "big", "small", "tall", "short", "long", "handsome", "plain", "quaint", "clean",
  "elegant", "easy", "angry", "crazy", "helpful", "mushy", "odd", "unsightly", "adorable", "important", "inexpensive",
  "cheap", "expensive", "fancy"];
const C = ["red", "yellow", "blue", "green", "pink", "brown", "purple", "brown", "white", "black", "orange"];
const N = ["table", "chair", "house", "bbq", "desk", "car", "pony", "cookie", "sandwich", "burger", "pizza", "mouse",
  "keyboard"];

let seed = 0;
// random function is replaced to remove any randomness from the benchmark.
const random = (max) => seed++ % max;

let nextId = 1;

function buildData(count) {
  const data = new Array(count);
  for (let i = 0; i < count; i++) {
    data[i] = {
      id: nextId++,
      label: `${A[random(A.length)]} ${C[random(C.length)]} ${N[random(N.length)]}`,
    }
  }
  return data;
}

const store = createStore((state = { data: [], selected: 0 }, action) => {
  const { data, selected } = state;
  switch (action.type) {
    case "RUN":
      return { data: buildData(1000), selected: 0 };
    case "RUN_LOTS":
      return { data: buildData(10000), selected: 0 };
    case "ADD":
      return { data: data.concat(buildData(1000)), selected };
    case "UPDATE": {
      const newData = data.slice();
      for (let i = 0; i < newData.length; i += 10) {
        const r = newData[i];
        newData[i] = { id: r.id, label: r.label + " !!!" };
      }
      return { data: newData, selected };
    }
    case "REMOVE": {
      const newData = data.slice();
      newData.splice(data.indexOf(action.item), 1);
      return { data: newData, selected };
    }
    case "SELECT":
      return { data, selected: action.id };
    case "CLEAR":
      return { data: [], selected: 0 };
    case "SWAP_ROWS": {
      const newData = data.slice();
      const tmp = newData[1];
      newData[1] = newData[998];
      newData[998] = tmp;
      return { data: newData, selected };
    }
  }
  return state;
});

const GlyphIcon = ({ preload = false }) => <span className={preload ? "preloadicon glyphicon glyphicon-remove" : "glyphicon glyphicon-remove"} aria-hidden="true"></span>;

const Row = React.memo(({ data }) => {
  const isSelected = useSelector((state) => state.selected === data.id);
  const dispatch = useDispatch();
  const select = useCallback(() => { dispatch({ type: "SELECT", id: data.id }); }, [data]);
  const remove = useCallback(() => { dispatch({ type: "REMOVE", item: data }); }, [data]);
  return (
    <tr className={isSelected ? "danger" : ""}>
      <td className="col-md-1">{data.id}</td>
      <td className="col-md-4"><a onClick={select}>{data.label}</a></td>
      <td className="col-md-1"><a onClick={remove}><GlyphIcon /></a></td>
      <td className="col-md-6"></td>
    </tr>
  )
});

const RowList = React.memo(() => {
  const rows = useSelector((state) => state.data);
  return rows.map((data) => <Row key={data.id} data={data} />);
});

const Button = React.memo(({ id, title, cb }) => (
  <div className="col-sm-6 smallpad">
    <button type="button" className="btn btn-primary btn-block" id={id} onClick={cb}>{title}</button>
  </div>
));

const Main = () => {
  const dispatch = useDispatch();
  const run = useCallback(() => { dispatch({ type: "RUN" }); }, []);
  const runLots = useCallback(() => { dispatch({ type: "RUN_LOTS" }); }, []);
  const add = useCallback(() => { dispatch({ type: "ADD" }); }, []);
  const update = useCallback(() => { dispatch({ type: "UPDATE" }); }, []);
  const clear = useCallback(() => { dispatch({ type: "CLEAR" }); }, []);
  const swapRows = useCallback(() => { dispatch({ type: "SWAP_ROWS" }); }, []);
  return (
    <div className="container">
      <div className="jumbotron">
        <div className="row">
          <div className="col-md-6"><h1>React + Redux</h1></div>
          <div className="col-md-6"><div className="row">
            <Button id="run" title="Create 1,000 rows" cb={run} />
            <Button id="runlots" title="Create 10,000 rows" cb={runLots} />
            <Button id="add" title="Append 1,000 rows" cb={add} />
            <Button id="update" title="Update every 10th row" cb={update} />
            <Button id="clear" title="Clear" cb={clear} />
            <Button id="swaprows" title="Swap Rows" cb={swapRows} />
          </div></div>
        </div>
      </div>
      <table className="table table-hover table-striped test-data"><tbody><RowList /></tbody></table>
      <GlyphIcon preload={true} />
    </div>
  );
};

ReactDOM.render(
  <Provider store={store}><Main /></Provider>,
  document.getElementById("main")
);
